## Travis CI Integration

language: c

install:
 - sudo apt-get apt-key
 - apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
 - sudo deb http://download.mono-project.com/repo/debian wheezy main
 - sudo apt-get update
 - sudo apt-get install mono-devel
 - sudo apt-get install mono-complete
 - sudo apt-get install nunit-console
 


script:
  - xbuild proyectofinal.sln
  - nunit-console proyectofinal/bin/Debug/proyectofinal.dll
