## Travis CI Integration

language: c

install:
 
 - sudo apt-get update
 - sudo apt-get autoremove
 - sudo apt-get install mono-devel
 - sudo apt-get install mono-complete
 - sudo apt-get install nunit-console
 
script:
  - xbuild proyectofinal.sln
  - nunit-console proyectofinal/bin/Debug/proyectofinal.dll
